#!/usr/bin/env bash

# -e: exit as soon as a command exit with a non-zero status code
# -u: prevent from any undefined variable
# -o pipefail: force pipelines to fail on the first non-zero status code
set -euo pipefail
# Avoid using space as a separator (default IFS=$' \t\n')
IFS=$'\n\t'

declare -r SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/tools/_all_tools.sh"

function main
{
    declare release_distributor_id
    declare release_codename
    declare -r script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

    ensure_user_is_in_sudoers || return "$?"

    identify_release "release_distributor_id" "release_codename" || return "$?"
    case "$release_distributor_id" in
        debian|ubuntu)
            # ok
            ;;
        *)
            error "This install is not compatible with your distribution '$release_distributor_id'"
            return 1
            ;;
    esac


    declare dir="$script_dir/before-install"
    for file in $(cd "$dir" && ls -1 *.sh | sort -n)
    do
        /usr/bin/env bash "$dir/$file" || true
    done

    section 'looking for software already installed'
    dir="$script_dir/software"
    declare software_name
    declare check_ok="\e[32m\xE2\x9C\x94\e[39m"
    declare check_fail="\e[31m\xE2\x9C\x98\e[39m"
    declare need_install=false

    for file in $(cd "$dir" && ls -1 *.sh | sort -n)
    do
        software_name="${file##[0-9][0-9]-}"
        software_name="${software_name%.sh}"
        if /usr/bin/env bash "$script_dir/software/$file" --exists
        then
            printf " %b %s\n" "$check_ok" "$software_name"
        else
            need_install=true
            printf " %b %s\n" "$check_fail" "$software_name"
        fi
    done

    if ${need_install}
    then
        dir="$script_dir/software"
        for file in $(cd "$dir" && ls -1 *.sh | sort -n)
        do
            /usr/bin/env bash "$dir/$file" || true
        done
    fi

    section "Post install"

    dir="$script_dir/post-install"
    for file in $(cd "$dir" && ls -1 *.sh | sort -n)
    do
        /usr/bin/env bash "$dir/$file" || true
    done

    section "Software versions"

    dir="$script_dir/software"
    for file in $(cd "$dir" && ls -1 *.sh | sort -n)
    do
        /usr/bin/env bash "$script_dir/software/$file" --version
    done
}

main
